### ISSUE TITLE
Ready for PHP 8.3?

### ISSUE THREAD

**Issue by JeroenDeDauw** [neo4j-php/neo4j-php-client#223] opened 2024-08-31 19:50 UTC
I see tests with PHP 8.1 and PHP 8.2 on GitHub Actions. Is this library supposed to work with 8.3 as well?

**Comment by exaby73** [comment] 2024-09-04 09:36
Hello @JeroenDeDauw. Yes this library should work with PHP 8.3. If you have any issues, please don't hesitate to open an issue describing your problem. Thank you

**Comment by transistive** [comment] 2024-09-04 11:15
Hey @exaby73 i don't think his question is just about 8.3 being supported, but also if it's well tested. He has a valid point that we don't have it tested in our GitHub Actions

**Comment by exaby73** [comment] 2024-11-13 07:30
Since we now have CI running on both 8.1 and 8.3, this should be confirmed to be working with 8.3. I'll close this issue for that reason. Thank you

**Closed by exaby73** 2024-11-13 07:30 UTC
Labels: enhancement
