### ISSUE TITLE
Run statements without transactions

### ISSUE THREAD

**Issue by bbaga** [neo4j-php/neo4j-php-client#64] opened 2021-07-15 14:45 UTC
The problem I'm running into is that I couldn't find a way to run statements without transactions.

Consider the following statement:
```
USING PERIODIC COMMIT 1000
LOAD CSV FROM 'file:///files.csv' AS line
CREATE (n:file {name: line[0]);
```

I could not run this statement because it will be wrapped around a transaction either way that cases an error.

An other issue that might be related to the forced transactions is the `Neo4j errors detected. First one with code "" and message "Read error"` error, which seems to happen when I'm running a hefty statement with lots of create, update or delete.
I used to run the same statements using `cypher-shell` and haven't had any issues that would resemble the "Read error".

What I tried to do is increasing the memory available for transactions in the Neo4j config, I'm at 3GB at the moment, but I still see these issues.

Any advice on how could I get around these problems?
| | |
|---|---|
| Server | Neo4j 4.1 CE |
| Library version | 2.0.5 |
| Driver | bolt |

**Comment by transistive** [comment] 2021-07-15 15:33
Hi @bbaga ,

Thank you for taking the time out of your day to address these issues.

The first use case you provided is very interesting. I never thought about it. I will make the necessary changes to make it work.

Regarding the second issue: it might be a stream timeout. Do these queries also take a long time?

I will fix both issues during the weekend.

Kind regards,

Ghlen

**Comment by bbaga** [comment] 2021-07-15 21:06
Hello Ghlen, thanks for the quick reply. Long time is relative, but we are talking about 10+ seconds.

**Comment by transistive** [comment] 2021-07-17 12:52
Hello @bbaga,

I have fixed both issues.

The first issue regarding the transaction auto commit should work starting from version 2.0.6.

The second issue regarding the read error was actually a socket timeout. I have now added some more tests, and you are now able to configure the transaction timeout for longer queries. Here are two examples of achieving the same thing with different means:

```php
// example 1: transaction functions
$client->writeTransaction(static function (TransactionInterface $tsx) {
    $tsx->run('UNWIND range(1, 10000) AS x MERGE (:Number {value: x})');
}, $alias, TransactionConfiguration::default()->withTimeout(100000));

// example 2: unmanged transactions
$tsx = $client->beginTransaction([], $alias, TransactionConfiguration::default()->withTimeout(100000));
$tsx->run('UNWIND range(1, 10000) AS x MERGE (:Number {value: x})');
```

Thank you for brining the issue to my attention. Please feel free to open a new issue when come across something else.

Kind regards,

Ghlen

**Comment by bbaga** [comment] 2021-07-19 13:14
👋 @transistive 
Thanks for the quick fix! 
The timeout issue when using transactions is solved and now I can use the periodic commits too, the issue is setting the timeout for the one-off statements 😄 

Use case: Importing large files with periodic commits

**Comment by transistive** [comment] 2021-07-19 14:36
Hello @bbaga ,

I will try and implement it tomorrow so you can also configure the timeout for one auto committed queries.

Thank you for your patience,

Ghlen

**Comment by bbaga** [comment] 2021-07-20 09:31
A little bit of additional info/request: I changed the library files locally to be able to pass the transaction config to the unmanaged transaction objects, now I'm seeing the following error:

> The allocation of 985.5 MiB would use more than the limit 1.5 GiB. Currently using 534.0 MiB. dbms.memory.transaction.max_size threshold reached (Neo.ClientError.General.Transa
  ctionOutOfMemoryError)
  
My understanding is that this means I'd have to bump up the `dbms.memory.transaction.max_size` value and that's it. The issue is, I'd rather not do that. In my use case I have to wipe the database as the first step of a process and at that time the size of the database is unknown. One option is to batch-delete nodes and relationships to reduce the memory footprint, but that complicates things a bit.

Is there a way to run the statements completely outside of transactions?

How I'm running the statement now (with locally modified library):
```php
$client->runStatement(
    Statement::create('MATCH (n:file) DETACH DELETE n'),
    null,
    TransactionConfiguration::default()->withTimeout(300)
);
```

**Comment by transistive** [comment] 2021-07-20 20:52
Hi @bbaga,

I have made it possible to set the socket timeout when building the driver or client, so even auto committed queries can have their runtime extended. Here is an example:

```php
$client = ClientBuilder::create()
    ->withDriver('default', 'bolt://test:test@test', null, 10000); //the final paramater is the timeout in seconds
    ->build();
```

**The change is available in version 2.0.7**

Regarding the transaction allocation: This is not a driver issue. You should iterate a query like this to reduce the memory usage:

```php
do {
   $count = $client->run(<<<'CYPHER'
       MATCH (n:file)
       WITH n LIMIT 10000
       DETACH DELETE n
       RETURN count(*) AS count;
       CYPHER
   )->first()->get('count') - 10000;
} while ($count > 0)
```

Good luck on your coding adventures!

Ghlen

**Closed** 2021-07-20 20:52 UTC

**Comment by noureldin-khaled** [comment] 2022-01-10 18:31
Hi @transistive :wave: 

I know this issue is closed, but I'm running into the same problem with the timeout. I'm setting my client as follows
```php
$url = 'bolt://test:test@neo4j:7687?database=test'
$this->client = ClientBuilder::create()
                             ->withDriver('bolt', $url, null, 3.0)
                             ->withDefaultTransactionConfiguration(TransactionConfiguration::default()->withTimeout(3.0))
                             ->withDefaultDriver('bolt')
                             ->build();
```

I know `3.0` is a really low value but I was just testing it out. This works for transactions only
```php
$tsx = $this->client->beginTransaction();
$result = $tsx->run("CALL apoc.util.sleep(10000)");
$tsx->commit();
```
It does timeout after 3 seconds with the error `Connection timeout reached after 3 seconds.` which is expected. However, I can't get it to work with the `run` function, so the following code doesn't timeout
```php
$result = $this->client->run("CALL apoc.util.sleep(10000)");
```
This doesn't timeout for some reason.

I tried debugging the code of the client and it appears that this part of the code is the reason
```php
/**
 * @return UnmanagedTransactionInterface<ResultFormat>
 */
private function beginInstantTransaction(SessionConfiguration $config): TransactionInterface
{
    $connection = $this->acquireConnection(TransactionConfiguration::default(), $config);

    return new BoltUnmanagedTransaction($this->config->getDatabase(), $this->formatter, $connection);
}

/**
 * @throws Exception
 *
 * @return ConnectionInterface<Bolt>
 */
private function acquireConnection(TransactionConfiguration $config, SessionConfiguration $sessionConfig): ConnectionInterface
{
    $timeout = max($this->socketTimeout, $config->getTimeout());

    return $this->pool->acquire($this->uri, $this->auth, $timeout, $this->userAgent, $sessionConfig);
}
```

The `$config->getTimeout()` part always returns `100000` which is the default timeout, so it overrides the passed `3.0` and this happens because it passed to it `TransactionConfiguration::default()` which has a null timeout so it always defaults to `100000`

Is this behavior intended? is there a way I can completely override the default timeout of `100000` to any value I want?
Also, what is the difference between the timeout passed to `withDriver` in `->withDriver('bolt', $url, null, 3.0)` and the one passed to `withDefaultTransactionConfiguration` in `->withDefaultTransactionConfiguration(TransactionConfiguration::default()->withTimeout(3.0))`? 
It appears that I need to set both of them for it to take effect on transactions, if I set one but not the other it doesn't work for transactions either, and nothing I tried worked for a one-off `run` query as I showed above. is there something I'm doing wrong with the configuration?

**Comment by transistive** [comment] 2022-01-10 23:06
Hi @noureldin-khaled,

Thank you for the great writedown. 

It is indeed working as intended at the moment. The transaction timeout is not really a transaction timeout, but a socket timeout. This is a limitation of the underlying library (Bolt). I can only implement timeouts if the requests are made none blocking. I am already talking to the author about this. Likewise, I will keep you updated! It shouldn't take too long before it gets implemented.

Kind regards,

Ghle
