### ISSUE TITLE
Deprecation warnings

### ISSUE THREAD

**Issue by seanlaneapg** [neo4j-php/neo4j-php-client#152] opened 2022-10-05 15:10 UTC
There is quite of couple of deprecated warnings .

{"message":"[2022-10-03T08:13:28.186646+00:00] php.INFO: Deprecated: Return type of Laudis\\Neo4j\\Enum\\SslMode::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice {\"exception\":\"[object] (ErrorException(code: 0): Deprecated: Return type of Laudis\\\\Neo4j\\\\Enum\\\\SslMode::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\\\\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice at /application/vendor/laudis/neo4j-php-client/src/Enum/SslMode.php:50)\"}

{"message":"[2022-10-03T08:13:28.190230+00:00] php.INFO: Deprecated: Return type of Laudis\\Neo4j\\Types\\AbstractCypherObject::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice {\"exception\":\"[object] (ErrorException(code: 0): Deprecated: Return type of Laudis\\\\Neo4j\\\\Types\\\\AbstractCypherObject::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\\\\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice at /application/vendor/laudis/neo4j-php-client/src/Types/AbstractCypherObject.php:53)\"}

{"message":"[2022-10-03T08:13:28.190481+00:00] php.INFO: Deprecated: Return type of Laudis\\Neo4j\\Types\\AbstractCypherObject::offsetGet($offset) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice {\"exception\":\"[object] (ErrorException(code: 0): Deprecated: Return type of Laudis\\\\Neo4j\\\\Types\\\\AbstractCypherObject::offsetGet($offset) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\\\\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice at /application/vendor/laudis/neo4j-php-client/src/Types/AbstractCypherObject.php:79)\"}

{"message":"[2022-10-03T08:13:28.399500+00:00] php.INFO: Deprecated: Return type of Laudis\\Neo4j\\Enum\\AccessMode::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice {\"exception\":\"[object] (ErrorException(code: 0): Deprecated: Return type of Laudis\\\\Neo4j\\\\Enum\\\\AccessMode::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\\\\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice at /application/vendor/laudis/neo4j-php-client/src/Enum/AccessMode.php:44)\"}

{"message":"[2022-10-03T08:13:28.420047+00:00] php.INFO: Deprecated: Return type of Laudis\\Neo4j\\Enum\\QueryTypeEnum::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice {\"exception\":\"[object] (ErrorException(code: 0): Deprecated: Return type of Laudis\\\\Neo4j\\\\Enum\\\\QueryTypeEnum::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\\\\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice at /application/vendor/laudis/neo4j-php-client/src/Enum/QueryTypeEnum.php:73)\"}

 - Library version: 2.4.4
 - Neo4j Version: 4.3
 - PHP version: 8.1.10
 - OS: Linux/Windows

**Comment by transistive** [comment] 2022-10-07 04:13
Hello @seanlaneapg,

Thank you for posting this issue.

It is a well known one and is fixed in version 2.5.0 and up. Please make sure to update the library. 

We can fix it if the issue persists on your end after that.

Good luck!

- Ghlen

**Comment by transistive** [comment] 2022-11-20 12:24
Closed due to inactivity and non-reproducibility

**Closed by transistive** 2022-11-20 12:24 UTC
Labels: bug
