### ISSUE TITLE
E_DEPRECATED:Implicit conversion from float 9.223372036854776E+18 to int loses precision

### ISSUE THREAD

**Issue by hetao29** [neo4j-php/neo4j-php-client#214] opened 2024-07-19 03:50 UTC
**Describe the bug**
```bash
E_DEPRECATED:Implicit conversion from float 9.223372036854776E+18 to int loses precision

vendor/laudis/neo4j-php-client/src/Types/AbstractCypherSequence.php(472) Generator::next()
6   ()  Laudis\Neo4j\Types\ArrayList::Laudis\Neo4j\Types\{closure}()
vendor/laudis/neo4j-php-client/src/Types/ArrayList.php(52)   Laudis\Neo4j\Types\AbstractCypherSequence::Laudis\Neo4j\Types\{closure}()
vendor/laudis/neo4j-php-client/src/Types/AbstractCypherSequence.php(99)  Laudis\Neo4j\Types\AbstractCypherSequence::current()
vendor/laudis/neo4j-php-client/src/Types/AbstractCypherSequence.php(447) Laudis\Neo4j\Types\AbstractCypherSequence::setupCache()
vendor/laudis/neo4j-php-client/src/Types/AbstractCypherSequence.php(529) E_DEPRECATED:Implicit conversion from float 9.223372036854776E+18 to int loses precision
```

**Desktop (please complete the following information):**
 - Library version: 3.1.0
 - Neo4j Version: 5.19
 - PHP version: 8.3.7 (cli) (built: May 30 2024 21:10:04) (NTS)
 - OS: Linux 5.15.0-107-generic #117-Ubuntu SMP Fri Apr 26 12:26:49 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

**Comment by exaby73** [comment] 2024-07-19 13:29
Hello @hetao29. This seems to be a duplicate of #207. Therefore, I'll close this one in favor of #207. Thank you

**Closed by exaby73** 2024-07-19 13:29 UTC
Labels: bug
